sonar.projectKey=NicolasOmar_moviegraphy
sonar.organization=nicolasomar

# relative paths to source directories. More details and properties are described
# in https://docs.sonarcloud.io/advanced-setup/analysis-scope/
sonar.sources=prisma/,src/,ts/
sonar.tests=prisma/,src/,ts/
sonar.inclusions=prisma/**/*.ts,src/**/*.tsx,ts/**/*.ts
sonar.exclusions=prisma/**/*.test.ts,src/**/*.test.tsx,ts/**/*.test.ts\
sonar.javascript.lcov.reportPaths=./coverage/lcov.info