name: Check code quality

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  codecovAndSonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: 1/7 | Checkout repo
      uses: actions/checkout@v7
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: 2/7 | Setup Node environment
      uses: actions/setup-node@v7
      with:
        node-version: 'latest'
    - name: 3/7 | Install depedencies
      run: npm ci
    - name: 4/7 | Run build script
      run: npm run build
    - name: 5/7 | Run unit tests suite
      run: npm run test:coverage
    - name: 6/7 | Run Codecov Uploader
      uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        fail_ci_if_error: true
        verbose: true
    - name: 7/7 | Run SonarCloud Scanner
      uses: sonarsource/sonarqube-scan-action@v8
      with:
        args: -Dproject.settings=configs/sonar-project.properties
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
